# NOTE: This file is synced from https://github.com/OrcaCollective/techbloc-directory
# Please see the .github/sync.yml file for sync information.
# (Note for maintainers, quarterly is not supported yet: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval)
---
version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "monthly"
      labels:
          - "dependency"
          - "pip"
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "monthly"
      labels:
          - "dependency"
          - "docker/env"
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "monthly"
      labels:
          - "dependency"
          - "npm"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
      labels:
          - "dependency"
          - "github-actions"
