language: python
dist: trusty
sudo: false
addons:
  firefox: "45.4.0esr"
python:
  - "2.7"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
before_script:
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - cd OpenOversight
script:
  - py.test -v --cov=app
after_success:
  - coveralls
