version: 2.1

steps:
  - &setup_dependencies
    run:
      name: Install dependencies (required for fabric)
      command: |
        pyenv global 3.5.2
        sudo apt-get install libpq-dev
        virtualenv --python=python3 .venv
        source .venv/bin/activate
        pip3 install -r requirements.txt
        pip3 install -r dev-requirements.txt

  - &add_ssh_keys
    add_ssh_keys:
      fingerprints:
        - "44:81:8d:36:86:55:fa:82:eb:97:65:f4:d7:9a:0b:fa"

  - &encrypt_and_save_backup
    run:
      name: Encrypt backup to shared GPG key, save to S3
      command: |
        export BACKUP_FILENAME=$(ls ~/project/backup/backup-*.tar.gz)

        # Not using keyservers because they are hot garbage, pubkey is in env var
        echo -e $GPG_KEY > OPENOVERSIGHT_GPG_PUB_KEY.asc
        gpg --import OPENOVERSIGHT_GPG_PUB_KEY.asc
        gpg --output backup.tar.gz.gpg --encrypt --trust-model always --batch --no-tty --recipient 0x3C4C259402A0E3B2 $BACKUP_FILENAME

        # Upload this encrypted backup to S3
        source .venv/bin/activate
        pip3 install awscli
        export TIMESTAMP=$(date +%s)
        cp backup.tar.gz.gpg backup-$TIMESTAMP.tar.gz.gpg
        aws s3 cp backup-$TIMESTAMP.tar.gz.gpg s3://openoversight-backups/

  - &backup_production
    run:
      name: Backup production server
      command: |
        source .venv/bin/activate
        fab production backup

jobs:
  lint:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Install lint dependencies and run linting
          command: |
            virtualenv .venv
            source .venv/bin/activate
            pip install flake8==3.5.0
            flake8 --ignore=E501,E722 --exclude=.venv/

  staging_backup_and_deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - *setup_dependencies
      - *add_ssh_keys

      #- run:
      #    name: Backup staging server
      #    command: |
      #      source .venv/bin/activate
      #      fab staging backup

      #- *encrypt_and_save_backup

      - run:
          name: Run migrations and deploy
          command: |
            source .venv/bin/activate
            fab staging migrate

  production_backup_and_deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - *setup_dependencies
      - *add_ssh_keys
      - *backup_production
      - *encrypt_and_save_backup

      - run:
          name: Run migrations and deploy
          command: |
            source .venv/bin/activate
            fab production migrate

  production_backup_only:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - *setup_dependencies
      - *add_ssh_keys
      - *backup_production
      - *encrypt_and_save_backup

workflows:
  per_pr:
    jobs:
      - lint
      - staging_backup_and_deploy
  staging_cd:
    jobs:
      - staging_backup_and_deploy:
          filters:
            branches:
              only: develop
  production_cd:
    jobs:
      - production_backup_and_deploy:
          filters:
            branches:
              only: master
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - production_backup_only
